// FAQ data for Mintsy platform

export interface FAQItem {
  id: string;
  question: string;
  answer: string;
}

export interface FAQCategory {
  id: string;
  title: string;
  icon?: React.ReactNode;
  items: FAQItem[];
}

// FAQ categories and questions
export const faqData: FAQCategory[] = [
  {
    id: "about",
    title: "About Mintsy",
    items: [
      {
        id: "what-is-mintsy",
        question: "What is Mintsy?",
        answer:
          "Mintsy is a creative AI art platform that lets you generate unique artwork from text prompts. You can mint your creations as NFTs, download high-definition images, and order printed canvases of your digital art.",
      },
      {
        id: "how-generation-works",
        question: "How does Mintsy generate artwork?",
        answer:
          "Mintsy uses advanced AI algorithms trained on millions of artworks to transform your text descriptions into unique digital art. Our technology understands artistic concepts, styles, and compositions to create images that match your creative vision.",
      },
      {
        id: "account-required",
        question: "Do I need to create an account to try it?",
        answer:
          "No, you don't need an account to try Mintsy. We offer one free artwork generation without sign-up so you can experience our platform. However, creating an account allows you to save your creations, access more features, and manage your subscription.",
      },
      {
        id: "artwork-uniqueness",
        question: "Is the artwork really unique?",
        answer:
          "Yes, each artwork generated by Mintsy is unique. While the AI has been trained on existing art styles, the combinations and interpretations it creates are one-of-a-kind. No two prompts will generate exactly the same artwork, even if they're similar.",
      },
    ],
  },
  {
    id: "art-downloads-prints",
    title: "Art, Downloads & Prints",
    items: [
      {
        id: "printing-options",
        question: "Can I print the art I create?",
        answer:
          "Absolutely! Mintsy offers high-quality canvas printing services for your digital creations. You can order prints directly through our platform and have them shipped to your door, ready to hang.",
      },
      {
        id: "available-sizes",
        question: "What sizes are available for canvas prints?",
        answer:
          "We offer multiple canvas print sizes to suit your space: Small (12×16''), Medium (18×2''), Large (24×36''), and Extra Large (36×48''). Custom sizes are also available upon request through our customer support.",
      },
      {
        id: "printing-cost",
        question: "How much does printing cost?",
        answer:
          "Canvas printing costs vary by size. Small prints start at €45, Medium at €75, Large at €120, and Extra Large at €180. Pro subscribers receive a 15% discount on all print orders. Shipping costs are calculated at checkout based on your location.",
      },
      {
        id: "watermark-on-prints",
        question: "Will my prints include a watermark?",
        answer:
          "No, all physical canvas prints are delivered without watermarks. Digital downloads with the Pro subscription are also watermark-free. Only the free tier digital downloads include a small Mintsy watermark.",
      },
    ],
  },
  {
    id: "subscriptions-payments",
    title: "Subscriptions & Payments",
    items: [
      {
        id: "pro-plan-features",
        question: "What's included in the Pro Plan?",
        answer:
          "The Pro Plan includes unlimited AI artwork generation, watermark-free high-resolution downloads, priority rendering, access to all art styles and advanced customization options, 15% discount on canvas prints, and early access to new features.",
      },
      {
        id: "one-time-purchase",
        question: "What if I only want one artwork?",
        answer:
          "We offer pay-as-you-go options for users who don't need a subscription. You can purchase single artwork generations, HD downloads, or specific features individually without committing to a monthly plan.",
      },
      {
        id: "cancellation-policy",
        question: "Can I cancel my subscription anytime?",
        answer:
          "Yes, you can cancel your subscription at any time. Your Pro access will continue until the end of your current billing period. There are no cancellation fees or long-term commitments with our subscription plans.",
      },
      {
        id: "refund-policy",
        question: "Do you offer refunds?",
        answer:
          "We offer a 7-day money-back guarantee for new Pro subscriptions if you're not satisfied with our service. For canvas prints, we offer refunds or replacements if there are quality issues or shipping damage. Please contact our support team for assistance with refunds.",
      },
    ],
  },
];
